apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/managed-by: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/name: "operand-deployment-lifecycle-manager"
    productName: IBM_Cloud_Platform_Common_Services
  name: operand-deployment-lifecycle-manager
  namespace: system
spec:
  selector:
    matchLabels:
      name: operand-deployment-lifecycle-manager
  replicas: 1
  template:
    metadata:
      labels:
        name: operand-deployment-lifecycle-manager
        app.kubernetes.io/instance: operand-deployment-lifecycle-manager
        app.kubernetes.io/managed-by: "operand-deployment-lifecycle-manager"
        app.kubernetes.io/name: "operand-deployment-lifecycle-manager"
        productName: IBM_Cloud_Platform_Common_Services
        intent: projected-odlm
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: "FREE"
    spec:
      serviceAccountName: operand-deployment-lifecycle-manager
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - command:
        - /manager
        args:
        - -v=1
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        image: icr.io/cpopen/odlm:latest
        imagePullPolicy: IfNotPresent
        name: manager
        livenessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 60
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 20
          failureThreshold: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 200Mi
            ephemeral-storage: 256Mi
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      terminationGracePeriodSeconds: 10
      serviceAccount: operand-deployment-lifecycle-manager
