# permissions for end users to edit operatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: operatorconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operand-deployment-lifecycle-manager
    app.kubernetes.io/part-of: operand-deployment-lifecycle-manager
    app.kubernetes.io/managed-by: kustomize
  name: operatorconfig-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - operatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - operatorconfigs/status
  verbs:
  - get
