
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operand-deployment-lifecycle-manager
rules:
- verbs:
    - get
    - list
    - watch
    - update
  apiGroups:
    - operator.ibm.com
  resources:
    - operandrequests
    - operandbindinfos
    - operandconfigs
    - operandregistries
- verbs:
    - patch
  apiGroups:
    - operator.ibm.com
  resources:
    - operandrequests
- apiGroups:
  - operator.ibm.com
  resources:
  - certmanagers
  - ibmlicensings
  - meteringreportservers
  - auditloggings
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - clusterhealth.ibm.com
  resources:
  - clusterservicestatuses
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - certmanager.k8s.io
  resources:
  - clusterissuers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - mutatingwebhookconfigurations
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: operand-deployment-lifecycle-manager
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
