apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operand-deployment-lifecycle-manager
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - catalogsources
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: operand-deployment-lifecycle-manager
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - operator.ibm.com
  resources:
  - operandconfigs
  - operandconfigs/status
  - operandregistries
  - operandregistries/status
  - operandrequests
  - operandrequests/status
  - operandbindinfos
  - operandbindinfos/status
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  - services
  - namespaces
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - route.openshift.io
  resources:
  - routes
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  - installplans
- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - k8s.keycloak.org
  resources:
  - keycloaks
