apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  labels:
    app.kubernetes.io/instance: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/managed-by: "operand-deployment-lifecycle-manager"
    app.kubernetes.io/name: "operand-deployment-lifecycle-manager"
  name: example-service
spec:
  requests:
  - registry: example-service
    operands:
    - name: jaeger
    - name: mongodb-atlas-kubernetes
